import Head from "next/head";
import AboutMain from "../components/about/AboutMain";
import ContactMain from "../components/contact/ContactMain";
import FooterMain from "../components/footer/FooterMain";
import HeroMain from "../components/hero/HeroMain";
import LayoutMain from "../components/layout/LayoutMain";
import ProjectsMain from "../components/projects/ProjectsMain";
import StackMain from "../components/stacks/StacksMain";
import WorkMain from "../components/work/WorkMain";

export default function Home() {
  return (
    <LayoutMain>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroMain />
      <WorkMain />
      <ProjectsMain />
      <StackMain />
      <AboutMain />
      <ContactMain />
      <FooterMain />
    </LayoutMain>
  );
}
